# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 510622b7fd30fc4e04de3a5ea41b3c8f79d00a75ac946d88d1e432f7750a65c743e0747c6002d9625e1a011e883f2d7eed9ab1763f570892e87a0f34457bd79b

test:
  secret_key_base: 9fcfba2a7dfed450316c70dc2d588356fa26c4661d40414a823219dcc6780662cdd70902843ae5063f62a744aaf692b10bea1228c6c161f459396bae94dc9bb5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
